name: CI

on: push

# env:
  # TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i
      - run: make lint build
